# Generated by Django 4.2.7 on 2026-02-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_add_avatar_url_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, choices=[('TECH', 'SNS College of Technology'), ('ARTS', 'Dr. SNS Rajalakshmi College of Arts and Science')], help_text='Campus assignment (Tech or Arts)', max_length=10, null=True),
        ),
    ]
