# Generated by Django 4.2.7 on 2026-01-29 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAnalyticsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_students", models.IntegerField(default=0)),
                ("total_mentors", models.IntegerField(default=0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("new_students_today", models.IntegerField(default=0)),
                ("new_submissions_today", models.IntegerField(default=0)),
                ("reviews_completed_today", models.IntegerField(default=0)),
                ("avg_system_completion", models.FloatField(default=0.0)),
                ("campuses_active", models.IntegerField(default=0)),
                ("floors_active", models.IntegerField(default=0)),
                ("avg_review_time_hours", models.FloatField(default=0.0)),
                ("pending_reviews_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Analytics Summary",
                "verbose_name_plural": "Global Analytics Summaries",
                "db_table": "analytics_global_summary",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="analytics_g_date_690db1_idx"),
                    models.Index(
                        fields=["last_updated"], name="analytics_g_last_up_97e8b5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FloorAnalyticsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campus", models.CharField(db_index=True, max_length=10)),
                ("floor", models.IntegerField(db_index=True)),
                ("total_students", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                ("assigned_students", models.IntegerField(default=0)),
                ("unassigned_students", models.IntegerField(default=0)),
                ("total_mentors", models.IntegerField(default=0)),
                ("active_mentors", models.IntegerField(default=0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("pending_reviews", models.IntegerField(default=0)),
                ("approved_submissions", models.IntegerField(default=0)),
                ("rejected_submissions", models.IntegerField(default=0)),
                ("clt_progress", models.FloatField(default=0.0)),
                ("cfc_progress", models.FloatField(default=0.0)),
                ("sri_progress", models.FloatField(default=0.0)),
                ("iipc_progress", models.FloatField(default=0.0)),
                ("scd_progress", models.FloatField(default=0.0)),
                ("avg_completion", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "computation_time_ms",
                    models.IntegerField(
                        default=0, help_text="Time taken to compute in milliseconds"
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor Analytics Summary",
                "verbose_name_plural": "Floor Analytics Summaries",
                "db_table": "analytics_floor_summary",
                "ordering": ["campus", "floor"],
                "indexes": [
                    models.Index(
                        fields=["campus", "floor"], name="analytics_f_campus_a65858_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="analytics_f_last_up_fdc92b_idx"
                    ),
                ],
                "unique_together": {("campus", "floor")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsComparisonLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("floor", "Floor"),
                            ("mentor", "Mentor"),
                            ("global", "Global"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(max_length=100)),
                ("live_value", models.JSONField()),
                ("cached_value", models.JSONField()),
                ("matches", models.BooleanField(default=True)),
                ("discrepancies", models.JSONField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("check_duration_ms", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Analytics Comparison Log",
                "verbose_name_plural": "Analytics Comparison Logs",
                "db_table": "analytics_comparison_log",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "checked_at"],
                        name="analytics_c_entity__aaf639_idx",
                    ),
                    models.Index(
                        fields=["matches"], name="analytics_c_matches_4e7dd2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MentorAnalyticsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_students_count", models.IntegerField(default=0)),
                ("pending_reviews_count", models.IntegerField(default=0)),
                ("total_reviews_completed", models.IntegerField(default=0)),
                (
                    "approval_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of approved submissions"
                    ),
                ),
                (
                    "avg_review_time_hours",
                    models.FloatField(
                        default=0.0, help_text="Average time to review in hours"
                    ),
                ),
                ("avg_student_completion", models.FloatField(default=0.0)),
                (
                    "students_at_risk",
                    models.IntegerField(
                        default=0, help_text="Students below 50% completion"
                    ),
                ),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("reviews_this_week", models.IntegerField(default=0)),
                ("reviews_this_month", models.IntegerField(default=0)),
                (
                    "workload_status",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("balanced", "Balanced"),
                            ("overloaded", "Overloaded"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.OneToOneField(
                        limit_choices_to={"profile__role": "MENTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_summary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor Analytics Summary",
                "verbose_name_plural": "Mentor Analytics Summaries",
                "db_table": "analytics_mentor_summary",
                "ordering": ["-assigned_students_count"],
                "indexes": [
                    models.Index(
                        fields=["workload_status"],
                        name="analytics_m_workloa_5612a4_idx",
                    ),
                    models.Index(
                        fields=["last_updated"], name="analytics_m_last_up_5c7225_idx"
                    ),
                    models.Index(
                        fields=["approval_rate"], name="analytics_m_approva_45be19_idx"
                    ),
                ],
            },
        ),
    ]
